language: php
php:
    - 5.5
    - 5.6
    - 7.0

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

script:
    - bin/generate-coverage-report.sh
    
after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    - travis_retry php -v
    - travis_retry composer update --no-interaction -o --prefer-dist
    - travis_retry composer show

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
